# Generated by Django 3.0.5 on 2020-06-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docNo', models.AutoField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=100)),
                ('busyTill', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patNo', models.AutoField(primary_key=True, serialize=False)),
                ('patname', models.CharField(max_length=100)),
                ('appointTime', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Doctor')),
            ],
        ),
    ]
