# Generated by Django 3.0.5 on 2020-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200618_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pats',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
