# Generated by Django 3.0.5 on 2020-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctor_pats'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='capacity',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
